server:
  port: 8080
  servlet:
    context-path: /api
    register-default-servlet: true
spring:
  application:
    name: yizhi_app
  #  redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
    # password: 123

tongyi:
  appId: 87423633
  appKey: xxxxxxxxxxxxxxx
  secretKey: xxxxxxxxxxxxxxxxxxxxx
  models:
    - modelName: ernie_speed
      timeInSeconds: 6
      numberVisits: 29
    - modelName: ernie-lite-8k
      timeInSeconds: 6
      numberVisits: 29
    - modelName: ernie-speed-128k
      timeInSeconds: 6
      numberVisits: 6
    - modelName: completions
      timeInSeconds: 6
      numberVisits: 29